import React, { useState } from 'react';
import { Code2, Copy, Check, X, CheckCircle } from 'lucide-react';

interface DiffViewerModalProps {
  isOpen: boolean;
  onClose: () => void;
  diffText?: string;
  filePath?: string;
}

export const DiffViewerModal: React.FC<DiffViewerModalProps> = ({
  isOpen,
  onClose,
  diffText,
  filePath = 'calculator.py'
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const defaultLines = [
    { type: 'header', text: '--- a/calculator.py' },
    { type: 'header', text: '+++ b/calculator.py' },
    { type: 'info', text: '@@ -1,3 +1,4 @@' },
    { type: 'context', text: ' def calculate_discount(price, discount_percent):' },
    { type: 'context', text: '     """Calculate final price after percentage discount."""' },
    { type: 'remove', text: '-    return price - discount_percent' },
    { type: 'add', text: '+    discount_amount = price * discount_percent / 100' },
    { type: 'add', text: '+    return price - discount_amount' },
  ];

  const diffLines = diffText
    ? diffText.split('\n').map((line) => {
        if (line.startsWith('+++') || line.startsWith('---') || line.startsWith('diff')) {
          return { type: 'header', text: line };
        }
        if (line.startsWith('@@')) {
          return { type: 'info', text: line };
        }
        if (line.startsWith('+')) {
          return { type: 'add', text: line };
        }
        if (line.startsWith('-')) {
          return { type: 'remove', text: line };
        }
        return { type: 'context', text: line };
      })
    : defaultLines;

  const copyDiff = () => {
    const raw = diffLines.map((d) => d.text).join('\n');
    navigator.clipboard.writeText(raw);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const addCount = diffLines.filter((l) => l.type === 'add').length;
  const removeCount = diffLines.filter((l) => l.type === 'remove').length;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="w-full max-w-4xl max-h-[85vh] rounded-2xl bg-[#0a0f24] border border-[#203260] shadow-2xl flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="p-4 px-6 border-b border-[#17254d] bg-[#0d1633] flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-rose-500/20 border border-rose-500/30 flex items-center justify-center text-rose-400">
              <Code2 className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-bold text-white">Git Diff Viewer</h2>
                <span className="text-xs text-rose-400 font-mono">
                  {filePath} (+{addCount} / -{removeCount} lines)
                </span>
              </div>
              <p className="text-xs text-slate-400">Autonomous code modification diff generated by agent</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={copyDiff}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#142145] hover:bg-[#1a2d5e] text-xs text-slate-300 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Patch'}</span>
            </button>
            <button onClick={onClose} className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-white/10">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Diff Code Container */}
        <div className="flex-1 p-5 bg-[#050813] font-mono text-xs overflow-auto select-text leading-relaxed">
          <div className="rounded-xl border border-[#17244a] overflow-hidden">
            {diffLines.map((line, idx) => {
              const isAdd = line.type === 'add';
              const isRemove = line.type === 'remove';
              const isInfo = line.type === 'info';
              const isHeader = line.type === 'header';

              return (
                <div
                  key={idx}
                  className={`flex items-start px-4 py-1 text-[11px] ${
                    isAdd
                      ? 'bg-emerald-950/30 text-emerald-300 border-l-2 border-emerald-400'
                      : isRemove
                      ? 'bg-rose-950/30 text-rose-300 border-l-2 border-rose-500'
                      : isInfo
                      ? 'bg-blue-950/20 text-blue-400 font-semibold'
                      : isHeader
                      ? 'bg-[#0d1633] text-slate-400 font-semibold'
                      : 'text-slate-300 hover:bg-white/[0.02]'
                  }`}
                >
                  <span className="w-8 select-none text-slate-600 font-mono text-[10px]">{idx + 1}</span>
                  <span className="flex-1 whitespace-pre">{line.text}</span>
                </div>
              );
            })}
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 px-6 bg-[#0c142b] border-t border-[#17254d] flex items-center justify-between text-xs">
          <div className="flex items-center gap-2 text-emerald-400 font-medium">
            <CheckCircle className="w-4 h-4" />
            <span>Passed AST validation & Pytest suite verification cleanly</span>
          </div>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white font-medium"
          >
            Close Viewer
          </button>
        </div>
      </div>
    </div>
  );
};
